### ISSUE TITLE
Unnecessary PropertyGroups for PlatformTarget?

### ISSUE THREAD

**Issue by AArnott** [microsoft/github-actions-for-desktop-apps#21]
Are all these really necessary?

https://github.com/microsoft/github-actions-for-desktop-apps/blob/d0fbf5cbc39057dea30244fb7ef6c5ae9c3b1ab8/MyWPFApp/MyWPFApp.csproj#L13-L35

It seems if defining these is necessary can't it be done in one step?

```xml
<PlatformTarget>$(Platform)</PlatformTarget> 
```

But I'd be surprised if that behavior isn't the default.

**Comment by edwardskrod** [comment]
Fixed by https://github.com/microsoft/github-actions-for-desktop-apps/pull/22
