### ISSUE TITLE
Letter of thank

### ISSUE THREAD

**Issue by lindexi** [microsoft/github-actions-for-desktop-apps#23]
After three hours, with the help of your documentation, I successfully passed the CI build, see https://github.com/dotnet-campus/TranslationTool/actions

![](https://user-images.githubusercontent.com/16054566/76585303-058dfa80-6519-11ea-95fb-9c1b7e56cc36.png)

I just want to share you what my mistake.

1. As #17 say, I should change the Upload build artifacts path
1. I forget to add the start project. And how to solve it, see https://github.com/dotnet-campus/TranslationTool/commit/2caac9931c3a582830ebb8d22d5b0eb62522f832
1. I forget to set the AppxBundlePlatforms in TranslationTool.Package.wapproj. And how to solve it, see https://github.com/dotnet-campus/TranslationTool/commit/107e6fd71ae6ef25500ba60a680031de626d4a9d
1. I forgot to remove the SigningCertificate code because my pfx has no keys. See https://github.com/dotnet-campus/TranslationTool/commit/58e47f75af2a611aaaaf3d6f08cc668a733f92f7
1. I forget to add the PublishProfiles files and which will cause the following errors to build. And how to solve it, see https://github.com/dotnet-campus/TranslationTool/commit/1650f7a9a12cc2a9df1595477f21a928507ea201

```
(ResolveAssemblyReferences target) ->   
C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): error MSB3270: There was a mismatch between the processor architecture of the project being built "AMD64" and the processor architecture of the reference "D:\a\TranslationTool\TranslationTool\Code\TranslationTool.WPF\bin\x86\Debug\netcoreapp3.1\win-x86\TranslationTool.WPF.dll", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project. [D:\a\TranslationTool\TranslationTool\Code\TranslationTool.Package\TranslationTool.Package.wapproj]
```

Thank you

**Comment by LanceMcCarthy** [comment]
LOL! Welcome to the club... this is what my build history looks like when first setting up an Azure Pipeline or GitHub Action for the first time on any project, too :)
