### ISSUE TITLE
[Question] Uap 19041 Support

### ISSUE THREAD

**Issue by LanceMcCarthy** [microsoft/github-actions-for-desktop-apps#29]
Hi Team,

I just updated my app's packaging project to use the 2004 SDK, but it looks like Actions isn't ready for it?

![image](https://user-images.githubusercontent.com/3520532/82737368-a3aef580-9cfe-11ea-9c7d-47c8f690ff3f.png)

If you want to see the build output, it's here (disregard the warnings, scroll to the bottom)  https://github.com/LanceMcCarthy/MediaFileManager/actions/runs/113382459

If you want to see the initiating PR, it's here https://github.com/LanceMcCarthy/MediaFileManager/pull/17

**Comment by edwardskrod** [comment]
The same thing happened to me when I targeted 10.0.19041.0:
https://github.com/microsoft/github-actions-for-desktop-apps/pull/30/checks?check_run_id=709249059

@chrispat Are the builds failing because the build machines don't have Windows 10 SDK, version 2004 on them?
https://developer.microsoft.com/en-us/windows/downloads/sdk-archive/

**Comment by chrispat** [comment]
Could be the the latest VS has not rolled out yet https://github.com/actions/virtual-environments/issues/932#issuecomment-632985706.

**Comment by LanceMcCarthy** [comment]
Yep, that's definitely the reason, however I'm not sure just updating to VS 16.6 is going to solve it, they'll also need the 19041 SDK. I'll leave a note in that thread to ask them to remember to include the SDK.

**Comment by edwardskrod** [comment]
I believe VS will make 19041 the 'out of the box' sdk here pretty soon

**Comment by LanceMcCarthy** [comment]
The solution for this is to update .NET Core from 3.1.100 to 3.1.x

**Comment by dampee** [comment]
> The solution for this is to update .NET Core from 3.1.100 to 3.1.x

for anyone using a search engine, you can really use `'3.1.x' according to the [github action documentation](https://github.com/actions/setup-dotnet)
