### ISSUE TITLE
Can i use this action to setup an app ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/github-actions-for-desktop-apps#50]
Is it possible to just use the action to install an app.exe in the GH runner so i can peform some automation test ?

**Comment by LanceMcCarthy** [comment]
Yes, you can download any file (e.g., exe, msi, etc) and run that installer. You use a PowerShell command to run any exe you want.

For example, you can use PowerShell...

```
Start-Process 'C:\Downloads\My.exe' -ArgumentList "/q" -Wait

Write-Output "My.exe installation complete."
```

Edit 1- edit reply to give concrete example

**Comment by amrsa1** [comment]
@LanceMcCarthy 
it stuck at this command, seems like the system waiting for some permission to be allowed  adding/removing runAs didnt help

<img width="903" alt="2022-11-30_23h08_54" src="https://user-images.githubusercontent.com/32042806/204919023-5349f161-95dc-4838-9b8c-5397eec21460.png">

**Comment by LanceMcCarthy** [comment]
I'm not an expert in using Powershell to start new processes. You'll probably get better assistance in stackexchange's https://superuser.com/

My firth thought is "does that installer require user interaction?" That would explain such behavior, check the evernote.exe launch args documentation to see if there's a way to execute it without user interaction. In my example, I pass the `/q` flag to the arguments list, but that doesn't mean it knows how to use it. 


Here are some screenshots on how I use the approach to install VS extensions (keep in mind is that Visual Studio and VSIX has the built-in capability to run userless via the /q flag).

![image](https://user-images.githubusercontent.com/3520532/204919710-09d5f66c-e3ce-4daa-9f87-9c6c81cf27cc.png)

**Comment by amrsa1** [comment]
@LanceMcCarthy that's awesome tips, thank you so much will take a look
